### ISSUE TITLE
usage: test1.py [-h] --image-left IMAGE_LEFT --image-right IMAGE_RIGHT                 --output-file OUTPUT_FILE test1.py: error: the following arguments are required: --image-left, --image-right, --output-file

### ISSUE THREAD

**Issue by HasanthaKarunachandra** [PacktPublishing/OpenCV-with-Python-By-Example#1]
How can I solve this problem.?

**Comment by shubham763** [comment]
Hi @HasanthaKarunachandra 
I would need to know which code "test1.py" you're executing and, second, which exact command. If you can provide me with that information I will be pleased to find an answer.

**Comment by shubham763** [comment]
Please reopen if the issue still persists.
